
import GlobalProvider from "@/components/GlobalProvider";
import "./globals.css";

export const metadata = {
  title: "NestMart | Next 13",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <GlobalProvider>
        {children}
        </GlobalProvider>
      </body>
    </html>
  );
}